---
- name: install openldap and python-ldap
  portage: package={{ item }}
  with_items:
    - net-nds/openldap
    - dev-python/python-ldap
  tags: packages

- name: ensure directories privileges
  file: >
    path={{ item }}
    state=directory
    owner=ldap group=ldap mode=0700
  with_items:
    - "{{ openldap_data_dir }}"
    - "{{ openldap_run_dir }}"

- name: remove useless config files
  file: >
    path={{ openldap_conf_dir }}/{{ item }}
    state=absent
  with_items:
    - ldap.conf.default
    - slapd.conf.default
    - slapd.ldif
    - slapd.ldif.default
    - DB_CONFIG.example
  tags: cleanup

- name: copy new schemas
  copy: >
    src={{ item.src }}
    dest={{ openldap_schema_dir }}/{{ item.name }}.schema
  with_items: openldap_schemas | select('mapping') | selectattr('src', 'defined') | list

- name: download external schemas
  get_url: >
    url={{ item.url }}
    dest={{ openldap_schema_dir }}/{{ item.name }}.schema
  with_items: openldap_schemas | select('mapping') | selectattr('url', 'defined') | list
