---
- include: install.yml tags=install
- include: configure.yml tags=configure

  # trigger handlers now to avoid unnecessary restarts and ensure that slapd
  # will be started after reindex
- meta: flush_handlers

- name: enable and start slapd
  service: name=slapd enabled=yes state=started
  tags: services

- name: populate LDAP from LDIF file
  ldap: >
    bind_dn={{ openldap_rootdn }}
    bind_password={{ openldap_rootpw }}
    src={{ openldap_populate_ldif }}
  when: openldap_populate_ldif != ""
  tags: populate
