---
- name: install openldap
  portage: package=net-nds/openldap

- name: ensure directories privileges
  file: >
    path={{ item }}
    state=directory
    owner=ldap group=ldap mode=0700
  with_items:
    - "{{ openldap_data_dir }}"
    - "{{ openldap_run_dir }}"

- name: remove useless config files
  file: >
    path={{ openldap_conf_dir }}/{{ item }}
    state=absent
  with_items:
    - ldap.conf.default
    - slapd.conf.default
    - slapd.ldif
    - slapd.ldif.default
    - DB_CONFIG.example
  tags: cleanup

- name: symlink DB_CONFIG to data directory
  file: >
    src={{ openldap_conf_dir }}/DB_CONFIG
    dest={{ openldap_data_dir }}/DB_CONFIG
    state=link